### ISSUE TITLE
Cannot find shared libraries

### ISSUE THREAD

**Issue by Codaero** [TommyChangUMD/ros-humble-ros1-bridge-builder#8]
I am trying to run the ros1-bridge on a new computer and I am unfortunately getting a "cannot open shared object file" error:

```code
codaero@codaero-Katana-17-B13VGK:~/ros-humble-ros1-bridge$ ros2 run ros1_bridge dynamic_bridge
/home/codaero/ros-humble-ros1-bridge/install/ros1_bridge/lib/ros1_bridge/dynamic_bridge: error while loading shared libraries: libroscpp.so.4d: cannot open shared object file: No such file or directory
[ros2run]: Process exited with failure 127
```

What may be causing this?

**Comment by TommyChangUMD** [comment]
hmm..  Did you source the overlay first?
`source ros-humble-ros1-bridge/install/local_setup.bash`

The libroscpp.so.4d file should be unpacked already and it's located at:

`ros-humble-ros1-bridge/install/ros1_bridge/lib/libroscpp.so.4d`

**Comment by Codaero** [comment]
Yes, I did the following when setting it up on a new PC:

```code
source /opt/ros/humble/setup.bash
source ros-humble-ros1-bridge/install/local_setup.bash
```

**Comment by TommyChangUMD** [comment]
Thank you for report this bug.  I've fixed it now.  
So, please pull the latest Dockerfile and try again.

**Comment by Codaero** [comment]
this works now thanks
